theme: jekyll-theme-minimal
title: Readings in the History of Programming
description: A list of resources intended for programmers, testers, software craftspeople and so on who care to understand the history of their profession.
